version: '3.7'
services:
  # MongoDB database
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 6972:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: squirrel
    volumes:
      - ./mongodb-setup.js:/docker-entrypoint-initdb.d/mongodb-setup.js:ro
  # MongoDB web app
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 9708:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
